name: fe_bookly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  vector_graphics: ^1.1.15

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bookly.svg
    - assets/images/backgroundlogin.png
    - assets/images/cover_buku/one day one ayat juz 1.jpg
    - assets/images/cover_buku/alphas destiny.jpg
    - assets/images/cover_buku/ralion.jpg
    - assets/images/cover_buku/true stalker.jpg
    - assets/images/cover_buku/eva si tokoh figuran.jpg
    - assets/images/cover_buku/ghost class.jpg
    - assets/images/cover_buku/a feather away.jpg
    - assets/images/cover_buku/linger.jpg
    - assets/images/cover_buku/mr. right.jpg
    - assets/images/cover_buku/not your princess.jpg
    - assets/images/cover_buku/oon in action.jpg
    - assets/images/cover_buku/terjebak kata sahabat.jpg
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
